name: Test Action

on:
  workflow_dispatch:  # Allows manual trigger from the Actions tab

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f2001499@ds.study.iitm.ac.in
        run: echo "Hello, world!"
